FROM golang:1.17.7-alpine3.15
WORKDIR /app
COPY . .
COPY supervisord.conf /etc/supervisord.conf
EXPOSE 80
RUN apk update --no-cache && apk add --no-cache tzdata redis supervisor;go env -w GO111MODULE=on;go env -w GOPROXY=https://goproxy.cn,direct
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN go mod tidy && go build -o luckwheelserver
ENTRYPOINT ["supervisord","-c"]
CMD ["/etc/supervisord.conf"]
